chainstore/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from chainstore import views
from django.contrib.flatpages.views import flatpage

urlpatterns = [

    path('admin/', admin.site.urls),

    path('', views.main, name='main'),
    path('main/', views.main, name='main'),
    path('', include('person.urls')),
    # path('person/', include('person.urls')),
    path('', include('place.urls')),
    # path('place/', include('place.urls')),
    path('', include('shop.urls')),
    path('shop/', include('shop.urls')),
    path('', include('shop.urls')),
    # path('shoptype/', include('shop.urls')),
    path('', include('warehouse.urls')),
    # path('warehouse/',include('warehouse.urls')),

    path('i18n/', include('django.conf.urls.i18n')),

    # path('message-form', views.message_form, name='message-form'),

    # authentication
    path('accounts/', include('django.contrib.auth.urls')),

    # flatpages
    re_path('(?P<url>.*)$', flatpage, name='flatpage'),
    # path('about/', flatpage, {'url': '/about/'}, name='about'),
    # path('terms/', flatpage, {'url': '/terms/'}, name='terms'),
    # path('pages/', include('django.contrib.flatpages.urls')),
]

"""
# experiments

# handler404 = 'chainstore.views.http404'
# handler404 = views.http404

    re_path('main/(?P<i>\d+)/(?P<j>\d+)/', views.main),
    re_path('main/(?P<i>\d+)/default/', views.main),
    re_path('main/(?P<i>\d+)/special/', views.main, kwargs={'j': -1}),
    re_path('post/(?P<slug>[\w\-]+)', views.post, name='news_post'),
    Experiments with person
    path('person/', include('person.urls')),
    re_path(r'^person/(?P<test>\w+)/', include('person.urls')),
    re_path(r'^person /(?P<pk>\d+)/', include([
        path('add',add, name='person_add'),
        path('edit',edit),
        path('remove', remove )
    ])),
"""

shop/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path, reverse_lazy
from shop.views import ShopList, CustomShopDetailView, ShopEdit, ShopDelete, ShopCreate, ShopUpdate
from shop.views import ShopTypeList, CustomShopTypeDetailView, ShopTypeEdit, ShopTypeDelete, test

urlpatterns = [

    # Shops
    path('shop/', login_required(ShopList.as_view()), name='shop'),
    re_path(r'^shop/(?P<pk>\d+)/$', login_required(CustomShopDetailView.as_view()), name='shop'),
    # re_path(r'^shop/(?P<pk>\d+)/$', ShopDetail.as_view(), name='shop'),
    # re_path(r'^shop/add$', ShopCreate.as_view(), name='shop_add'),
    re_path(r'^shop/(?P<pk>\d+|new)/edit$', login_required(ShopEdit.as_view()), name='shop_edit'),
    re_path(r'^shop/(?P<pk>\d+)/delete$', login_required(ShopDelete.as_view()), name='shop_delete'),

    # Shop Types
    path('shoptype/', ShopTypeList.as_view(), name='shoptype'),
    re_path(r'^shoptype/(?P<pk>\d+)/$', CustomShopTypeDetailView.as_view(), name='shoptype'),
    # re_path(r'^shoptype/(?P<pk>\d+)/$', ShopTypeDetail.as_view(), name='shoptype'),
    re_path(r'^shoptype/(?P<pk>\d+|new)/edit$', login_required(ShopTypeEdit.as_view()), name='shoptype_edit'),
    re_path(r'^shoptype/(?P<pk>\d+)/delete$', login_required(ShopTypeDelete.as_view()), name='shoptype_delete'),

    path('shop/test', test),
]

shop/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import F
from django.urls import reverse

from person.models import Person
from warehouse.models import Warehouse
from place.models import City
from django.utils.translation import ugettext_lazy as _


class ShopType(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_('name'))
    description = models.TextField(verbose_name=_('description'))

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Shop(models.Model):
    name = models.CharField(max_length=50, verbose_name=_('name'))
    shop_type = models.ForeignKey(ShopType, verbose_name=_('type'), on_delete=models.PROTECT)
    owner = models.ForeignKey(Person, verbose_name=_('owner'), related_name='shop_owner', on_delete=models.PROTECT)
    address = models.CharField(max_length=250, verbose_name=_('address'), blank=True)
    city = models.ForeignKey(City, verbose_name=_('city'), on_delete=models.PROTECT)
    website = models.URLField(verbose_name=_('website'), blank=True)
    sellers = models.ManyToManyField(Person, verbose_name=_('sellers'), related_name='sellers')
    warehouses = models.ManyToManyField(Warehouse, verbose_name=_('warehouses'))
    version = models.PositiveIntegerField(verbose_name=_('version'), default=0, editable=False)

    class Meta:
        verbose_name = _('shop')
        verbose_name_plural = _('shops')
        ordering = ('name', 'city')

    def __str__(self):
        return f'{self.name} | {self.shop_type} | {self.city}'

    def get_absolute_url(self):
        return reverse('shop', kwargs={'pk': self.pk})


"""
    def get_absolute_url(self):
        return reverse('shop_detail', kwargs={'pk': self.pk})

    @models.permalink
    def get_absolute_url(self):
        return 'shop', (), {'pk': self.pk}
"""


@receiver(post_save, sender=Shop)
def inc_shop_version(sender, instance, **kwargs):
    Shop.objects.filter(pk=instance.pk).update(version=F('version') + 1)

shop/forms.py
from django import forms
from shop.models import Shop, ShopType


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'


class ShopTypeForm(forms.ModelForm):
    class Meta:
        model = ShopType
        fields = '__all__'

shop/views.py
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import PermissionDenied
from django.db.models import Prefetch
from django.urls import reverse_lazy
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView, TemplateView

from shop.forms import ShopForm, ShopTypeForm
from shop.models import Shop, ShopType
from person.models import Person
from warehouse.models import Warehouse

# __ Shop views _________________________________________________________________
"""
def shop_list(request):
    return render(
        request,
        'shop_list.html',
        {
            'shops': Shop.objects.all(),
            'main_menu_key': 'shops',
        },
    )
"""


class ShopList(ListView):
    # model = Shop
    queryset = Shop.objects.select_related('shop_type', 'owner', 'city', 'city__country')
    context_object_name = 'shops'
    # template_name = 'shop/shop_list.html'
    paginate_by = 10
    paginate_orphans = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_menu_key'] = 'shops'
        return context


"""
def shop_detail(request, pk):
    return render(request, 'shop_detail.html', {
        'shop': get_object_or_404(Shop, pk=pk),
        'main_menu_key': 'shops',
    })
"""


class ShopDetail(DetailView):
    queryset = Shop.objects.select_related(
        'shop_type', 'owner', 'city', 'city__country',
    ).prefetch_related(
        Prefetch('sellers', Person.objects.order_by()),
        Prefetch('warehouses', Warehouse.objects.select_related('city', 'city__country'))
    )
    # model = Shop
    context_object_name = 'shop'
    template_name = 'shop/shop_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_menu_key'] = 'shops'
        return context


class CustomShopDetailView(TemplateView):
    template_name = 'shop/shop_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shop'] = get_object_or_404(Shop, pk=kwargs['pk'])
        context['main_menu_key'] = 'shops'
        return context


class ShopEdit(TemplateView):
    template_name = 'shop/shop_edit.html'

    def dispatch(self, request, *args, **kwargs):
        if kwargs['pk'] != 'new':
            self.instance = get_object_or_404(Shop, pk=kwargs['pk'])
        else:
            self.instance = None
        self.form = ShopForm(request.POST or None, instance=self.instance)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_menu_key'] = 'shops'
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        if self.form.is_valid():
            saved_instance = self.form.save()
            if not self.instance:
                messages.success(request, 'Successfully created!')
            else:
                messages.success(request, 'Successfully saved!')
            return redirect('shop_edit', pk=saved_instance.pk)
        return self.get(request, *args, **kwargs)


class ShopUpdate(PermissionRequiredMixin, UpdateView):
    model = Shop
    fields = ('name', 'shop_type', 'owner', 'address', 'city', 'sellers', 'warehouses', 'website')
    # template_name = 'shop/shop_edit.html'


class ShopCreate(PermissionRequiredMixin, CreateView):
    model = Shop
    fields = ('name', 'shop_type', 'owner', 'address', 'city', 'sellers', 'warehouses', 'website')


class ShopDelete(PermissionRequiredMixin, DeleteView):
    model = Shop
    success_url = reverse_lazy('shop')
    permission_required = 'shop.delete_shop'

    def handle_no_permission(self):
        if self.raise_exception:
            raise PermissionDenied(self.get_permission_denied_message())
        return redirect_to_login(self.request.get_full_path(), self.get_login_url(), self.get_redirect_field_name())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_menu_key'] = 'shops'
        return context


# __ ShopType views _________________________________________________________________
"""
def shoptype_list(request):
    return render(request, 'shoptype_list.html', {
        'shoptypes': ShopType.objects.all(),
        'main_menu_key': 'shoptypes',
    })
"""


class ShopTypeList(ListView):
    model = ShopType
    context_object_name = 'shoptypes'
    template_name = 'shop/shoptype_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_menu_key'] = 'shoptypes'
        return context


"""
def shoptype_detail(request, pk):
    return render(request, 'shoptype_detail.html', {
        'shoptype': get_object_or_404(Shoptype, pk=pk),
        'main_menu_key': 'shoptypes',
    })


class ShopTypeDetail(DetailView):
    model = ShopType
    context_object_name = 'shoptype'
    template_name = 'shop/shoptype_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_menu_key'] = 'shoptypes'
        return context
"""


class CustomShopTypeDetailView(TemplateView):
    template_name = 'shop/shoptype_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shoptype'] = get_object_or_404(ShopType, pk=kwargs['pk'])
        context['main_menu_key'] = 'shoptypes'
        return context


class ShopTypeEdit(TemplateView):
    template_name = 'shop/shoptype_edit.html'

    def dispatch(self, request, *args, **kwargs):
        if kwargs['pk'] != 'new':
            self.instance = get_object_or_404(ShopType, pk=kwargs['pk'])
        else:
            self.instance = None
        self.form = ShopTypeForm(request.POST or None, instance=self.instance)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_menu_key'] = 'shoptypes'
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        if self.form.is_valid():
            saved_instance = self.form.save()
            if not self.instance:
                messages.success(request, 'Successfully created!')
            else:
                messages.success(request, 'Successfully saved!')
            return redirect('shoptype_edit', pk=saved_instance.pk)
        return self.get(request, *args, **kwargs)


class ShopTypeDelete(PermissionRequiredMixin, DeleteView):
    model = ShopType
    success_url = reverse_lazy('shoptype')
    permission_required = 'shoptype.delete_shoptype'

    def handle_no_permission(self):
        if self.raise_exception:
            raise PermissionDenied(self.get_permission_denied_message())
        return redirect_to_login(self.request.get_full_path(), self.get_login_url(), self.get_redirect_field_name())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['main_menu_key'] = 'shoptypes'
        return context


# __ experiments ____________________________________________________________________
def test(request):
    return render(request, 'shop/test/test.html', {
        'a': '<b>hello</b>',
        'b': ['<b>hello</b>', '<i>world</i>', ],
        'd': {'a': 1, 'b': {'z': 4}, 'c': 3},
        'obj': Shop.objects.first(),
        'x': 4,
        'r': range(20),
        't0': '',
        't1': 'Hello',
        't2': 'World',
        'items': Shop.objects.all(),
        'items2': [
            {'name': 'Aaa', 'n': 1},
            {'name': 'Aaa', 'n': 2},
            {'name': 'Bbb', 'n': 3},
        ],
        'y': 5,
        'list1': [1, 2],
        'list2': [3, 4],
        'yy': "'hello'",
        'zz': 'hello',
        'xx': datetime.now(),
        'aa': 'Hello Person!',
        'bb': 123213423542,
        'cc': 1.28,
        'dd': '?q=поиск',
        'ee': (
            'Text Текст\n'
            'text текст\n\n'
            'New Paragraph'
        ),
        'ff': datetime(2013, 1, 1),
        'gg': datetime(2019, 1, 1),
        't': '<b>very</b> interesting page' * 100,
        'test': '<b> t e s t </b>',
        'time_now': timezone.now(),
        'date_prefix': 'Date: ',
        'selected_menu': 0,
    })

shop/templates/shop/menu.html
<ul>
    {% for item in items %}
        <li>
            {% if selected == forloop.counter0 %}
                <b>{{ item }}</b>
            {% else %}
                {{ item }}
            {% endif %}
        </li>
    {% endfor %}
</ul>

shop/templates/shop/shop_confirm_delete.html
{% include 'chainstore/_confirm_delete.html' with page_title='Shops' item_name=shop %}

shop/templates/shop/shop_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {{ shop }} | {% trans 'shops'|capfirst %} | {{ WEBSITE }}
{% endblock %}

{% block content %}

    <h1>{% trans 'shops'|capfirst %}: {{ shop }}</h1>

    <form>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'name'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                {{ shop.name }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'type'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                <a href="{% url 'shoptype' pk=shop.shop_type.pk %}">{{ shop.shop_type }}</a>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'owner'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                <a href="{% url 'person' pk=shop.owner.pk %}">{{ shop.owner }} ({{ shop.owner.email|urlize }})</a>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'address'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                {{ shop.address }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'city'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                <a href="{% url 'city' pk=shop.city.pk %}"> {{ shop.city.name }}</a>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'country'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                <a href="{% url 'country' pk=shop.city.country.pk %}">{{ shop.city.country.name }}</a>
            </div>
        </div>

        {% if shop.website %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">{% trans 'website'|capfirst %}:</label>
                <div class="col-sm-10 form-control-plaintext">
                    {{ shop.website|urlize }}
                </div>
            </div>
        {% endif %}

        {% if shop.sellers.all %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">{% trans 'sellers'|capfirst %}:</label>
                <div class="col-sm-10 form-control-plaintext">
                    {% for seller in shop.sellers.all %}
                        <p>{{ forloop.counter }}) <a href="{% url 'person' pk=seller.pk %}">{{ seller }}</a>
                            ({{ seller.email|urlize }})</p>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if shop.warehouses.all %}
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">{% trans 'warehouses'|capfirst %}:</label>
                <div class="col-sm-10 form-control-plaintext">
                    {% for warehouse in shop.warehouses.all %}
                        <p>{{ forloop.counter }}) <a href="{% url 'warehouse' pk=warehouse.pk %}">{{ warehouse }}</a>
                        </p>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">id:</label>
            <div class="col-sm-10 form-control-plaintext">
                {{ shop.pk }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'version'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                {{ shop.version }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                {% if perms.shop.add_shop %}
                    {% include 'chainstore/button_edit.html' %}
                {% endif %}
                {% if perms.shop.delete_shop %}
                    {% include 'chainstore/button_delete.html' %}
                {% endif %}
                {% include 'chainstore/button_goback.html' %}
            </div>
        </div>

    </form>

    {% comment %} v1
    <p>Shop ID: #{{ shop.pk }}</p>
    <p>Name: {{ shop.name }}</p>
    <p>Type: <a href="{% url 'shoptype' pk=shop.shop_type.pk %}">{{ shop.shop_type }}</a></p>
    <p>Owner: <a href="{% url 'person' pk=shop.owner.pk %}">{{ shop.owner }} ({{ shop.owner.email|urlize }})</a></p>
    <p>Address: {{ shop.address }}</p>
    <p>City: <a href="{% url 'city' pk=shop.city.pk %}"> {{ shop.city.name }}</a></p>
    <p>Country: <a href="{% url 'country' pk=shop.city.country.pk %}">{{ shop.city.country.name }}</a></p>

    {% if shop.sellers.all %}
        <p>Sellers:</p>
        {% for seller in shop.sellers.all %}
            <ul>
                <li><a href="{% url 'person' pk=seller.pk %}">{{ seller }}</a> ({{ seller.email|urlize }})</li>
            </ul>
        {% endfor %}
    {% endif %}

    {% if shop.warehouses.all %}
        <p>Warehouses:</p>
        {% for warehouse in shop.warehouses.all %}
            <ul>
                <li><a href="{% url 'warehouse' pk=warehouse.pk %}">{{ warehouse }}</a></li>
            </ul>
        {% endfor %}
    {% endif %}

    {% if shop.website %}
        <p>Website: {{ shop.website|urlize }}</p>
    {% endif %}


    {% include 'chainstore/buttons_edit_delete_goback.html' %}

    {#    <div class="btn-group" role="group" aria-label="Basic example">#}
    {#        <a href="edit"><button type="button" class="btn btn-outline-primary">{% trans 'Edit' %}</button></a>#}
    {#        <a href="delete"><button type="button" class="btn btn-outline-danger">Delete</button></a>#}
    {#        <a href="{% url 'shop' %}"><button type="button" class="btn btn-outline-secondary">Back to the List</button></a>#}
    {#    </div>#}

{% endcomment %}

{% endblock %}

shop/templates/shop/shop_edit.html
{% include 'chainstore/_edit.html' with page_title='Shops' page_back_button_url='shop' %}

shop/templates/shop/shop_list.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {% trans 'shops'|capfirst %} | {{ WEBSITE }}
{% endblock %}

{% block content %}

    {#    <h1>{% trans 'shops'|capfirst %} <span class="badge badge-pill badge-primary">{{ shops|length }}</span></h1>#}
    <h1>{% trans 'shops'|capfirst %} <span class="badge badge-pill badge-primary">{{ page_obj.paginator.count }}</span>
    </h1>

    {% if perms.shop.add_shop %}
        {% include "chainstore/button_add.html" %}
    {% endif %}

        {% include "chainstore/pagination.html" %}

    {% if shops %}

        <table class="table">

            <thead>
            <tr>
                <th>#</th>
                <th>{% trans 'Name'|capfirst %}</th>
                <th>{% trans 'Type'|capfirst %}</th>
                <th>{% trans 'Owner'|capfirst %}</th>
                <th>{% trans 'Country'|capfirst %}</th>
                <th>{% trans 'City'|capfirst %}</th>
                <th>{% trans 'Address'|capfirst %}</th>
                <th>{% trans 'Website'|capfirst %}</th>
                <th>id</th>
                <th>{% trans 'version'|capfirst %}</th>
                {% if perms.shop.add_shop %}
                    <th></th>
                {% endif %}

            </tr>
            </thead>

            <tbody>

            {% for shop in shops %}
                <tr>
                    <td><a href="{% url 'shop' pk=shop.pk %}">{{ page_obj.start_index|add:forloop.counter0 }}</a></td>
                    <td><a href="{% url 'shop' pk=shop.pk %}">{{ shop.name }}</a></td>
                    <td><a href="{% url 'shoptype' pk=shop.shop_type.pk %}">{{ shop.shop_type }}</a></td>
                    <td><a href="{% url 'person' pk=shop.owner.pk %}">{{ shop.owner }}</a></td>
                    <td><a href="{% url 'country' pk=shop.city.country.pk %}">{{ shop.city.country.name }}</a></td>
                    <td><a href="{% url 'city' pk=shop.city.pk %}">{{ shop.city.name }}</a></td>
                    <td>{{ shop.address }}</td>
                    <td>{{ shop.website|urlize }}</td>
                    <td><a href="{% url 'shop' pk=shop.pk %}">{{ shop.pk }}</a></td>
                    <td><a href="{% url 'shop' pk=shop.pk %}">{{ shop.version }}</a></td>
                    {% if perms.shop.add_shop %}
                        <td><a href="{% url 'shop' pk=shop.pk %}edit">
                            <button type="button" class="btn btn-outline-secondary">{% trans 'Edit' %}</button>
                        </a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}

            </tbody>

        </table>

        {% include "chainstore/pagination.html" %}

    {% else %}
        <p class="text-muted">
            <i>List of Shops is empty.</i>
        </p>

    {% endif %}

    {% if perms.shop.add_shop %}
        {% include "chainstore/button_add.html" %}
    {% endif %}

{% endblock %}

shop/templates/shop/shoptype_confirm_delete.html
{% include 'chainstore/_confirm_delete.html' with page_title='Shop Types' item_name=shoptype %}

shop/templates/shop/shoptype_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {{ shoptype }} | {% trans 'Shop Types'|capfirst %} | {{ WEBSITE }}
{% endblock %}

{% block content %}

    <h1>{% trans 'Shop Types'|capfirst %}: {{ shoptype }}</h1>

    <form>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'Name'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                {{ shoptype.name }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">id:</label>
            <div class="col-sm-10 form-control-plaintext">
                {{ shoptype.pk }}
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">{% trans 'description'|capfirst %}:</label>
            <div class="col-sm-10 form-control-plaintext">
                {{ shoptype.description }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                {% if perms.shop.add_shoptype %}
                    {% include 'chainstore/button_edit.html' %}
                {% endif %}
                {% if perms.shop.delete_shoptype %}
                    {% include 'chainstore/button_delete.html' %}
                {% endif %}
                {% include 'chainstore/button_goback.html' %}
            </div>
        </div>

    </form>

    {% comment %} v1
    <p>Name: {{ shoptype.name }}</p>
    <p>id: {{ shoptype.pk }}</p>
    <p>{{ shoptype.description }}</p>
    <br>
    <a href="edit">
        <button type="button" class="btn btn-outline-primary">{% trans 'Edit' %}</button>
    </a>
    <a href="delete">
        <button type="button" class="btn btn-outline-danger">Delete</button>
    </a>
    <a href="{% url 'shoptype' %}">
        <button type="button" class="btn btn-outline-secondary">Back to the List</button>
    </a>

    {#    <br>#}
    {#    <a href="{% url 'shoptype' %}"><<< Back to the Shop Types</a>#}
{%  endcomment %}

{% endblock %}

shop/templates/shop/shoptype_edit.html
{% include 'chainstore/_edit.html' with page_title='Shop Types' page_back_button_url='shoptype' %}

shop/templates/shop/shoptype_list.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {% trans 'Shop Types'|capfirst %} | {{ WEBSITE }}
{% endblock %}

{% block content %}

    <h1>{% trans 'Shop Types'|capfirst %} <span class="badge badge-pill badge-primary">{{ shoptypes|length }}</span>
    </h1>

    {% if perms.shop.add_shoptype %}
        {% include "chainstore/button_add.html" %}
    {% endif %}

    {% if shoptypes %}

        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>{% trans 'Name'|capfirst %}</th>
                <th>id</th>
                {% if perms.shop.add_shoptype %}
                    <th></th>
                {% endif %}
            </tr>
            </thead>

            <tbody>
            {% for shoptype in shoptypes %}
                <tr>
                    <td><a href="{% url 'shoptype' pk=shoptype.pk %}">{{ forloop.counter }}</a></td>
                    <td><a href="{% url 'shoptype' pk=shoptype.pk %}">{{ shoptype.name }}</a></td>
                    <td><a href="{% url 'shoptype' pk=shoptype.pk %}">{{ shoptype.pk }}</a></td>
                    {% if perms.shop.add_shoptype %}
                        <td>
                            <a href="{% url 'shoptype' pk=shoptype.pk %}edit">
                                <button type="button" class="btn btn-outline-secondary">{% trans 'Edit' %}</button>
                            </a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}

        <p class="text-muted">
            <i>List of Shop Types is empty.</i>
        </p>

    {% endif %}

    {% if perms.shop.add_shoptype %}
        {% include "chainstore/button_add.html" %}
    {% endif %}

{% endblock %}

shop/templates/shop/x.html
<b>Hello! block x</b>
<p> {{ items }}</p>
<p> {{ items|join:', ' }}</p>
<p> {{ a }}</p>
<p> {{ a|join:' ' }}</p>